apiVersion: v1
kind: Service
metadata:
  name: telegraf
spec:
  ports:
  - port: 4999
    protocol: TCP
    name: http
  selector:
    app: telegraf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: c-telegraf
  labels:
    app: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      serviceAccountName: telegraf
      containers:
      - name: telegraf
        image: mytelegraf
        ports:
        - containerPort: 4999
        imagePullPolicy: Never
        env:
          - name: INFLUX_USER
            value: admin
          - name: INFLUX_URL
            value: "http://influxdb:8086"
          - name: INFLUX_SKIP_DATABASE_CREATION
            value: "false"
          - name: INFLUX_PASSWORD
            value: "123456789"
          - name: INFLUX_TOKEN
            valueFrom:
              secretKeyRef:
                name: telegraf
                key: INFLUX_TOKEN
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
---
apiVersion: v1
kind: Secret
metadata:
  name: telegraf
  # namespace: kube-system
data:
  # printf "somevar" | base64
  INFLUX_TOKEN: NDQ3R3VMQlBBVEpRVzNxWEwxN0VxNkxQWGgtdlJlZFRUZ1JLZ18xUFY1cU01a3lWaWhCNEl0cm5XSU8wMGpoMVdINm9kUGhhbmQyZ1U5aHpGMTZrekE9PQ==
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: telegraf
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: telegraf
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: telegraf
  labels:
    app: influxdb